port: 8080
grpc:
  port: 50051

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  name: some-project
  sslmode: disable

mongodb:
  uri: mongodb://admin:password@localhost:27017/some-project?authSource=admin

swagger: true
log:
  level: info
  format: json
